#!/bin/bash

#shc -f lzkm 
#shc -f lzkmconfig

pack=/media/thomas/Dev/applications/lz_kernel_manager/lz_kernel_manager_1.9.2/usr/local/bin
cp lzkm $pack/lzkm
cp lzkmconfig $pack/lzkmconfig
cp lzcolordef $pack/lzcolordef
#rm *.x.c
#rm *.x

cd /media/thomas/Dev/applications/lz_kernel_manager
dpkg-deb --build --root-owner-group lz_kernel_manager_1.9.2
mv *.deb Releases 
